### ISSUE TITLE
13th June peer-to-peer code review

### ISSUE THREAD

**Issue by lewisjn-arch** [George7h/Portfolio#2]
#### Highlights

- [x] Your work looks really good and is an exact copy of the figma template.
- [x] You have made a good decision on just animating the images so that the page doesn't look overcrowded with animations.

#### Improvements

- [x] You can add animations on the social media icons to make the area more user interactive.

**Comment by George7h** [comment]
Thank you so much for the feedback. I will do the needful improvements.
<img src="https://media4.giphy.com/media/ZfK4cXKJTTay1Ava29/giphy.gif"/>

**Comment by lucy-sees** [comment]
## Hi @George7h , 

Your project is looking great!   
Congratulations! 🎉 

## To Highlight
- All linters are passing ✔️ 
- Descriptive commit messages ✔️ 
- Professional looking issue ✔️ 
- Good overall design ✔️ 
![7E2e](https://github.com/George7h/George7h.github.io/assets/100368317/b9bc4d59-205a-452c-8d08-72765e327494)

Cheers and Happy coding!👏👏👏
