### ISSUE TITLE
Peer-to-peer-code-review

### ISSUE THREAD

**Issue by NalianAchei2020** [George7h/Portfolio#7]
Great Job
# Highlights
- Good job with implementing the validations +1:
-  Please remove unused comments in your code. This helps you write better code

**Comment by George7h** [comment]
Good day @NalianAchei2020,

Thank you so much for the feedback. I will implement the necessary changes as required.
<img src="https://media0.giphy.com/media/fxI1G5PNC5esyNlIUs/giphy.gif"/>
